name: Deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Update appsettings.json
      run: |
        echo '{"ServicesUrlOptions": { "ApiBaseUrl": "ApiBaseUrl" }}' > appsettings.json
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish Blazor WebAssembly using dotnet
      run: dotnet publish -c Release --no-build -o publishoutput
    - name: Deploy generated Blazor WebAssembly to Netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        args: deploy --dir=publishoutput/wwwroot --prod
        secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
